### PR TITLE
Bug fix for test_target_teams_distribute_reduction_sub.F90

### PR DESCRIPTION
**Pull request by spophale**
Addressing Issue #87 reported. Needs to be tested.

### CODE REVIEW

**Comment by jhdavis8** [comment]
I don't think we can remove this error var since it is referenced on lines 50 and 53 to track errors in the test_sub function

**Comment by jhdavis8** [comment]
@jhdavis8 ah nevermind, I see it is coming from the outer scope.

**Comment by spophale** [comment]
Tested with xlf on summit.

**Comment by josemonsalve2** [comment]
Errors is only needed within the function, I feel it might be better to remove the outer one and leave the inner one, initialized

**Comment by jhdavis8** [comment]
> Errors is only needed within the function, I feel it might be better to remove the outer one and leave the inner one, initialized

I agree with this

**Comment by spophale** [comment]
There needs to be consistency across tests. Does not matter where.

**Comment by jhdavis8** [comment]
> There needs to be consistency across tests. Does not matter where.

Looking at other Fortran tests, many of them have a useless/redundant `INTEGER:: errors` in the outer context that could be removed. I think the best solution is to make a PR (I can do it) to remove all of these since it is clearer if the errors var is defined in the context is used in.

**Pull request merged**
