### PR TITLE
Add fixed version of default_firstprivate test

### PR DESCRIPTION
**Pull request by jhdavis8**
Addressing issue #129. My proposed fix is to add data sharing attributes for the arrays that have been improperly made firstprivate. However, the "first" part of the test is still failing on gfortran, but I am hesitant to file a bug report until we are sure because they have already ruled a bug report from me as invalid for this test (due to the issue this PR is fixing). See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94290.

### CODE REVIEW

**Comment by tob2** [comment]
There is in any case an issue in the second function `test_firstprivate_first`. One has:
```
    !$omp target teams distribute default(firstprivate) map(alloc:d) …
```
which is the same as
```
!$omp target map(alloc:d)
! d is not initialized here
!$omp teams distribute default(firstprivate)
do …
   d = …  ! d is firstprivate here as instructed
end do …
! team distributed ends here;
! d is still uninitialized 
```
i think you want to add `shared(d)` to the `omp target teams` …

**Comment by tob2** [comment]
Any progress? With my additional change – adding `shared(x)`, it does work for me when testing. (Besides making sense semantically.)

**Comment by jhdavis8** [comment]
@tob2 Sorry I missed your first comment! I will correct this today

**Comment by jhdavis8** [comment]
Fixed, passes Summit gfortran and xlf. Thanks @tob2 !

**Comment by tob2** [comment]
What's actually the status of this pull request? There are two approvals – since a week. it is also marked as `ready`. (For what it is worth: the PR also looks fine to me.)

Only the third requested reviewer (@josemonsalve2) has not commented/approved it, yet.

**Comment by jhdavis8** [comment]
It looks ready, I'll go ahead and merge.

**Pull request merged**
