### PR TITLE
Flipped values for USM macro var, now default value is zero to indica…

### PR DESCRIPTION
**Pull request by andrewkallai**
…te no USM present

### CODE REVIEW

**Review by fel-cab — APPROVED** [review]

**Comment by fel-cab** [comment]
@andrewkallai is going to add the tests that rely on the macro before we approve it.

**Comment by andrewkallai** [comment]
All C tests which rely on the macro have been reviewed.

**Comment by fel-cab** [comment]
@andrewkallai are you going to add, to this commit, the C tests that rely this macro and have to be changed?

**Comment by andrewkallai** [comment]
No changes are needed so no tests need to be added.

**Comment by spophale** [comment]
@andrewkallai , since the behavior is reversed, will the tests not need updating as well ?

**Comment by andrewkallai** [comment]
Case 1: existing tests make use of OMPVV_TEST_SHARED_ENVIRONMENT;
Because this macro is used for reporting purposes and has no effect on the program besides defining internal macro variables, no change is needed as long as the program does not depend on those internal variables (which is the actual case).
Case 2: existing tests make use of OMPVV_TEST_AND_SET_SHARED_ENVIRONMENT(var2set);
This can affect program behavior if var2set is used in the program. Thus, if the program relies on the previous definition logic, the test has to be changed. I found this to not be the case for existing tests, so no changes have to be made.
Note: I have not included the Fortran tests into consideration, which I will change in a seperate PR.

**Review by spophale — APPROVED** [review]

**Pull request merged**
