### PR TITLE
ompt_state_wait_barrier_implementation test

### PR DESCRIPTION
**Pull request by mjcarr458**

### CODE REVIEW

**Comment by mjcarr458** [comment]
Change to parallel and check within region.

**Comment by spophale** [comment]
@fel-cab will test with ompt enabled compiler.

**Comment by andrewkallai** [comment]
frontier
clang 18.0.0
test_ompt_state_wait_barrier_implementation.c:30:19: error: call to undeclared function 'ompt_get_state'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   30 |                 int state_val = ompt_get_state();
      |                                 ^
/autofs/nccs-svm1_home1/andrewka/sollve_vv/tests/5.1/ompt/test_ompt_state_wait_barrier_implementation.c:30:19: note: did you mean 'ompd_get_state'?
/autofs/nccs-svm1_sw/frontier/ums/ums012/llvm/17.0.0-20230726/lib/clang/18/include/omp-tools.h:1347:11: note: 'ompd_get_state' declared here
 1347 | ompd_rc_t ompd_get_state(ompd_thread_handle_t *thread_handle,
      |           ^
1 error generated.

**Comment by spophale** [comment]
I don't think this test does what we are hoping to verify. I vote we steer clear from ompt and ompd  interfaces.

**Comment by andrewkallai** [comment]
I agree since we decided to avoid the other ompt PR as well.

**Comment by fel-cab** [comment]
It also agree

**Pull request closed without merging**
