### PR TITLE
New test/reduction separated directives.c (issue #35)

### PR DESCRIPTION
**Pull request by jhdavis8**
See issue #35. This is a test of the reduction clause with an and operator, using separated target teams parallel for directives. The test tries to perform the same calculation using both a reduction and atomic writes. I added a C and C++ version.

Both are passing the compilers on fatnode. Summit is down for maintenance today.

### CODE REVIEW

**Comment by jhdavis8** [comment]
Fixed the data races by having only team 0 do the writes.

**Comment by jhdavis8** [comment]
Right now this test is passing gnu but failing clang on fatnode. Need to submit a bug report.

**Comment by spophale** [comment]
@jhdavis8 
Is there a reason not to merge the test ?

**Comment by josemonsalve2** [comment]
It's waiting on bug report

**Comment by jhdavis8** [comment]
Just tested on summit and clang and the tests are passing all compilers. Not sure what the cause of the errors I saw earlier was, so I will remove the label and merge this.

**Pull request merged**
